version: '3.8'

services:
  db:
    image: postgres:16
    container_name: coredb
    environment:
      POSTGRES_DB: coredb
      POSTGRES_USER: coreuser
      POSTGRES_PASSWORD: corepass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coreuser -d coredb"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
